sudo: false

language:
  - python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

before_install:
    - pip install --upgrade pytest

install:
  - pip install pytest-cov python-coveralls
  - pip install -r requirements.txt

script:
  - py.test -vv;
    

notifications:
  email: false

